In [31]:
import pandas as pd
df = pd.read_csv("data.csv")

In [32]:
df

     Name  Age       City  Salary  Experience
0   Rahul   22     Mumbai   35000           1
1   Priya   24       Pune   42000           2
2    Amit   21      Delhi   30000           0
3   Sneha   23  Bangalore   50000           3
4  Vikram   25    Chennai   45000           2

In [33]:
# How to apply filters 
df[df["Name"] == "Rahul"]

    Name  Age    City  Salary  Experience
0  Rahul   22  Mumbai   35000           1

In [34]:
df[df["Age"] >= 23]

     Name  Age       City  Salary  Experience
1   Priya   24       Pune   42000           2
3   Sneha   23  Bangalore   50000           3
4  Vikram   25    Chennai   45000           2

In [35]:
df[df["Salary"] < 35000]

   Name  Age   City  Salary  Experience
2  Amit   21  Delhi   30000           0

In [36]:
# @ above one is about applying only 1 condition
# what if you want to apply multiple conditiiosn?
# &(and) , |(or)
# every condition will be in seperate bracate

In [42]:
# Example: i want to have the people whose experience is greater than 2 years and
# salary greater than 40000

df1 = df[(df["Experience"]>=2) & (df["Salary"] >= 40000)]
df1
# This is how you can write down more than 1 condition=

     Name  Age       City  Salary  Experience
1   Priya   24       Pune   42000           2
3   Sneha   23  Bangalore   50000           3
4  Vikram   25    Chennai   45000           2

In [46]:
# either experience greater than 1 year or salary greater than 50k 
df2 = df[(df["Experience"]>1) | (df["Salary"]>=50000)] 
df2

     Name  Age       City  Salary  Experience
1   Priya   24       Pune   42000           2
3   Sneha   23  Bangalore   50000           3
4  Vikram   25    Chennai   45000           2

In [47]:
# Groupby , orderby , apply , converting datatype from 1 to another for dataframe columns

In [ ]:
# sklearn