In [24]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 103, 105],
    "Name": [
        "Rahul", "Priya", "Amit", "Sneha", "Vikram", "Neha",
        "Arjun", "Pooja", "Rohan", "Anjali", "Amit", "Vikram"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "IT", "HR",
        "Finance", "IT", "HR", "Finance", "IT", "IT"
    ],
    "Age": [25, 28, 24, 30, 27, None, 26, 29, 31, 25, 24, 27],
    "Salary": [
        50000, 45000, 55000, 60000, None, 48000,
        65000, 52000, 47000, 58000, 55000, None
    ],
    "City": [
        "Mumbai", "Pune", "Mumbai", "Delhi", "Bangalore", "Pune",
        "Delhi", "Mumbai", "Bangalore", "Delhi", "Mumbai", None ],
    "Experience": [2, 3, 1, 5, 4, 3, 6, 2, 7, 2, 1, 4]
}

df = pd.DataFrame(data)
df

    Employee_ID    Name Department   Age   Salary       City  Experience
0           101   Rahul         IT  25.0  50000.0     Mumbai           2
1           102   Priya         HR  28.0  45000.0       Pune           3
2           103    Amit         IT  24.0  55000.0     Mumbai           1
3           104   Sneha    Finance  30.0  60000.0      Delhi           5
4           105  Vikram         IT  27.0      NaN  Bangalore           4
5           106    Neha         HR   NaN  48000.0       Pune           3
6           107   Arjun    Finance  26.0  65000.0      Delhi           6
7           108   Pooja         IT  29.0  52000.0     Mumbai           2
8           109   Rohan         HR  31.0  47000.0  Bangalore           7
9           110  Anjali    Finance  25.0  58000.0      Delhi           2
10          103    Amit         IT  24.0  55000.0     Mumbai           1
11          105  Vikram         IT  27.0      NaN        NaN           4

In [25]:
df.head() # top 5 records

   Employee_ID    Name Department   Age   Salary       City  Experience
0          101   Rahul         IT  25.0  50000.0     Mumbai           2
1          102   Priya         HR  28.0  45000.0       Pune           3
2          103    Amit         IT  24.0  55000.0     Mumbai           1
3          104   Sneha    Finance  30.0  60000.0      Delhi           5
4          105  Vikram         IT  27.0      NaN  Bangalore           4

In [26]:
df.tail() # bottom 5 records

    Employee_ID    Name Department   Age   Salary       City  Experience
7           108   Pooja         IT  29.0  52000.0     Mumbai           2
8           109   Rohan         HR  31.0  47000.0  Bangalore           7
9           110  Anjali    Finance  25.0  58000.0      Delhi           2
10          103    Amit         IT  24.0  55000.0     Mumbai           1
11          105  Vikram         IT  27.0      NaN        NaN           4

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  12 non-null     int64
 1   Name         12 non-null     str
 2   Department   12 non-null     str
 3   Age          11 non-null     float64
 4   Salary       10 non-null     float64
 5   City         11 non-null     str
 6   Experience   12 non-null     int64
dtypes: float64(2), int64(2), str(3)
memory usage: 970.0 bytes

In [28]:
df.isnull().sum()

Employee_ID    0
Name           0
Department     0
Age            1
Salary         2
City           1
Experience     0
dtype: int64

In [29]:
df["City"].mode()[0]

'Mumbai'

In [30]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df["City"] = df["City"].fillna("Manchester")

In [31]:
df.isnull().sum()

Employee_ID    0
Name           0
Department     0
Age            0
Salary         0
City           0
Experience     0
dtype: int64

In [32]:
df

    Employee_ID    Name Department        Age   Salary        City  Experience
0           101   Rahul         IT  25.000000  50000.0      Mumbai           2
1           102   Priya         HR  28.000000  45000.0        Pune           3
2           103    Amit         IT  24.000000  55000.0      Mumbai           1
3           104   Sneha    Finance  30.000000  60000.0       Delhi           5
4           105  Vikram         IT  27.000000  53500.0   Bangalore           4
5           106    Neha         HR  26.909091  48000.0        Pune           3
6           107   Arjun    Finance  26.000000  65000.0       Delhi           6
7           108   Pooja         IT  29.000000  52000.0      Mumbai           2
8           109   Rohan         HR  31.000000  47000.0   Bangalore           7
9           110  Anjali    Finance  25.000000  58000.0       Delhi           2
10          103    Amit         IT  24.000000  55000.0      Mumbai           1
11          105  Vikram         IT  27.000000  53500.0  Manchester           4

In [34]:
# Filtering of the data 
# we will create new dataframes 
df1 = df[df["City"] == "Mumbai"]
df1

    Employee_ID   Name Department   Age   Salary    City  Experience
0           101  Rahul         IT  25.0  50000.0  Mumbai           2
2           103   Amit         IT  24.0  55000.0  Mumbai           1
7           108  Pooja         IT  29.0  52000.0  Mumbai           2
10          103   Amit         IT  24.0  55000.0  Mumbai           1

In [37]:
df2 = df[df["City"] == "Bangalore"]
df2

   Employee_ID    Name Department   Age   Salary       City  Experience
4          105  Vikram         IT  27.0  53500.0  Bangalore           4
8          109   Rohan         HR  31.0  47000.0  Bangalore           7

In [42]:
df3 = df[(df["Salary"] >= 50000) & (df["City"] == "Mumbai")]
df3

    Employee_ID   Name Department   Age   Salary    City  Experience
0           101  Rahul         IT  25.0  50000.0  Mumbai           2
2           103   Amit         IT  24.0  55000.0  Mumbai           1
7           108  Pooja         IT  29.0  52000.0  Mumbai           2
10          103   Amit         IT  24.0  55000.0  Mumbai           1

In [44]:
df3 = df[(df["Salary"] >= 50000) | (df["Age"] >=25)]
df3["Salary"] = df3["Salary"]/2

In [56]:
def refactor(x):
    b = f"{x:.2f}"
    return float(b)

In [60]:
df3["Age"] = df3["Age"].apply(int)

In [61]:
df3

    Employee_ID    Name Department  Age   Salary        City  Experience
0           101   Rahul         IT   25  25000.0      Mumbai           2
1           102   Priya         HR   28  22500.0        Pune           3
2           103    Amit         IT   24  27500.0      Mumbai           1
3           104   Sneha    Finance   30  30000.0       Delhi           5
4           105  Vikram         IT   27  26750.0   Bangalore           4
5           106    Neha         HR   26  24000.0        Pune           3
6           107   Arjun    Finance   26  32500.0       Delhi           6
7           108   Pooja         IT   29  26000.0      Mumbai           2
8           109   Rohan         HR   31  23500.0   Bangalore           7
9           110  Anjali    Finance   25  29000.0       Delhi           2
10          103    Amit         IT   24  27500.0      Mumbai           1
11          105  Vikram         IT   27  26750.0  Manchester           4

In [54]:
x = 2.23456765433
b = f"{x:.2f}"
b

'2.00'