In [1]:

import pandas as pd

data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115],
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Vikas",
             "Neha", "Rohit", "Pooja", "Karan", "Anjali",
             "Suresh", "Meera", "Akash", "Riya", "Nikhil"],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "Sales", "HR",
                   "Sales", "Finance", "IT", "Sales", "Finance"],
    "Age": [25, 29, 32, 28, 35, 27, 40, 30, 26, 31,
            38, 33, 24, 29, 36],
    "Gender": ["Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male"],
    "Salary": [45000, 52000, 75000, 60000, 48000,
               65000, 85000, 70000, 40000, 55000,
               62000, 72000, 42000, 50000, 80000],
    "Experience": [2, 4, 8, 5, 6, 3, 12, 7, 1, 5,
                   9, 8, 1, 3, 10],
    "City": ["Pune", "Mumbai", "Bengaluru", "Pune", "Mumbai",
             "Bengaluru", "Pune", "Mumbai", "Pune", "Bengaluru",
             "Mumbai", "Pune", "Bengaluru", "Mumbai", "Pune"],
    "PerformanceRating": [4, 5, 4, 3, 4, 5, 3, 4, 3, 4,
                          5, 4, 3, 4, 5]
}

df = pd.DataFrame(data)

df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [2]:
# groupby 
df.groupby("Department")["Salary"].mean()

Department
Finance    74250.000000
HR         51666.666667
IT         59400.000000
Sales      50666.666667
Name: Salary, dtype: float64

In [3]:
# groupby 
df.groupby("Department")["Salary"].max()

Department
Finance    85000
HR         55000
IT         75000
Sales      62000
Name: Salary, dtype: int64

In [4]:
# groupby 
df.groupby("Department")["Salary"].min()

Department
Finance    60000
HR         48000
IT         42000
Sales      40000
Name: Salary, dtype: int64

In [5]:
# orderby 
df.sort_values(by= "Salary" , ascending = False)

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
11,112,Meera,Finance,33,Female,72000,8,Pune,4
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
0,101,Rahul,IT,25,Male,45000,2,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
8,109,Karan,Sales,26,Male,40000,1,Pune,3

In [6]:
# orderby 
df.sort_values(by= "Salary" , ascending= True)

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
8,109,Karan,Sales,26,Male,40000,1,Pune,3
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
0,101,Rahul,IT,25,Male,45000,2,Pune,4
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
11,112,Meera,Finance,33,Female,72000,8,Pune,4
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3

In [7]:
# in sql you can apply groupby on the data with conditions 
# here you should have condition applied forst and on that data we will apply the groupby

In [8]:
df2 = df.sort_values(by = "Department")

In [9]:
df2

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
11,112,Meera,Finance,33,Female,72000,8,Pune,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
0,101,Rahul,IT,25,Male,45000,2,Pune,4
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
8,109,Karan,Sales,26,Male,40000,1,Pune,3
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4

In [10]:
df2 = df[df["Salary"]>=50000]

In [11]:
df2["Department"].unique()

<ArrowStringArray>
['HR', 'IT', 'Finance', 'Sales']
Length: 4, dtype: str

In [12]:
df2.sort_values(by = "Department").sort_values(by = "City").sort_values(by = "Salary")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
11,112,Meera,Finance,33,Female,72000,8,Pune,4
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3

In [13]:
# in some methods there is the arg inplace = True
# inplace = True then original dataframe will change 

# but if you are not using inplace = True then you can declare diffrent dataframes variables
# you are doing operation on df dataframe 
# and saving change in df = df.operation()
# in this case origibnal df will change

In [14]:
# del df
# df

# NameError Traceback (most recent call last)
# Cell In[30], line 1
# ----> 1 df
# NameError: name 'df' is not defined

In [23]:
df.to_excel("filename.xlsx" , index = False)

In [26]:
df = pd.read_excel("filename.xlsx")

In [27]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [28]:
import pandas as pd

data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115],
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Vikas",
             "Neha", "Rohit", "Pooja", "Karan", "Anjali",
             "Suresh", "Meera", "Akash", "Riya", "Nikhil"],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "Sales", "HR",
                   "Sales", "Finance", "IT", "Sales", "Finance"],
    "Age": [25, 29, 32, 28, 35, 27, 40, 30, 26, 31,
            38, 33, 24, 29, 36],
    "Gender": ["Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male"],
    "Salary": [45000, 52000, 75000, 60000, 48000,
               65000, 85000, 70000, 40000, 55000,
               62000, 72000, 42000, 50000, 80000],
    "Experience": [2, 4, 8, 5, 6, 3, 12, 7, 1, 5,
                   9, 8, 1, 3, 10],
    "City": ["Pune", "Mumbai", "Bengaluru", "Pune", "Mumbai",
             "Bengaluru", "Pune", "Mumbai", "Pune", "Bengaluru",
             "Mumbai", "Pune", "Bengaluru", "Mumbai", "Pune"],
    "PerformanceRating": [4, 5, 4, 3, 4, 5, 3, 4, 3, 4,
                          5, 4, 3, 4, 5]
}

df = pd.DataFrame(data)

df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [30]:
df.to_csv("employee.csv" ,index = False)

In [31]:
pd.read_csv("employee.csv")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Reyansh Nagar,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Dharavi,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Wakad,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [32]:
df.to_csv("employee1.csv" , index = False)

In [33]:
pd.read_csv("employee1.csv")

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Sujata Nagar,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Sujata Nagar,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Sujata Nagar,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Sujata Nagar,5